"""Column metadata for model metrics and walk-forward comparison tables."""

from __future__ import annotations

from nfl_predictor.api.registry.columns import ColumnMeta, register

METRICS = "Metrics"
CANDIDATE = "Candidate"

register(
    ColumnMeta(
        "brier",
        "Brier",
        "Mean squared error of the win probability. Lower is better; 0.25 is a coin flip.",
        METRICS,
        "float",
        "lower",
        heatmap=True,
        decimals=4,
    ),
    ColumnMeta(
        "log_loss",
        "Log loss",
        "Negative log likelihood of the outcomes under the win probabilities. Lower is better.",
        METRICS,
        "float",
        "lower",
        heatmap=True,
        decimals=4,
    ),
    ColumnMeta(
        "reliability_ece",
        "ECE",
        "Expected calibration error: average gap between predicted and observed win rate across probability bins. Lower is better.",
        METRICS,
        "float",
        "lower",
        heatmap=True,
        decimals=4,
    ),
    ColumnMeta(
        "pick_accuracy",
        "Pick acc.",
        "Share of games where the favored side won.",
        METRICS,
        "prob",
        "higher",
        heatmap=True,
        decimals=1,
    ),
    ColumnMeta(
        "winner_accuracy",
        "Winner acc.",
        "Share of holdout games where the favored side won.",
        METRICS,
        "prob",
        "higher",
        heatmap=True,
        decimals=1,
    ),
    ColumnMeta(
        "margin_mae",
        "Margin MAE",
        "Mean absolute error of the predicted margin, in points.",
        METRICS,
        "float",
        "lower",
        heatmap=True,
        decimals=2,
    ),
    ColumnMeta(
        "total_mae",
        "Total MAE",
        "Mean absolute error of the predicted total, in points.",
        METRICS,
        "float",
        "lower",
        heatmap=True,
        decimals=2,
    ),
    ColumnMeta(
        "home_mae",
        "Home MAE",
        "Mean absolute error of the home score.",
        METRICS,
        "float",
        "lower",
        decimals=2,
    ),
    ColumnMeta(
        "away_mae",
        "Away MAE",
        "Mean absolute error of the away score.",
        METRICS,
        "float",
        "lower",
        decimals=2,
    ),
    ColumnMeta(
        "expected_points_avg",
        "Exp. pool pts",
        "Average expected confidence-pool points per week.",
        METRICS,
        "float",
        "higher",
        heatmap=True,
        decimals=1,
    ),
    ColumnMeta(
        "actual_points_avg",
        "Actual pool pts",
        "Average realized confidence-pool points per week.",
        METRICS,
        "float",
        "higher",
        heatmap=True,
        decimals=1,
    ),
    ColumnMeta(
        "market_margin_resid_mae",
        "Margin MAE vs mkt",
        "Margin MAE of the model relative to the market baseline.",
        METRICS,
        "float",
        "lower",
        decimals=2,
    ),
    ColumnMeta(
        "market_total_resid_mae",
        "Total MAE vs mkt",
        "Total MAE relative to the market baseline.",
        METRICS,
        "float",
        "lower",
        decimals=2,
    ),
    ColumnMeta("games", "Games", "Games evaluated.", METRICS, "int"),
    ColumnMeta("weeks", "Weeks", "Weeks evaluated.", METRICS, "int"),
    ColumnMeta("candidate_key", "Key", "Candidate identifier.", CANDIDATE),
    ColumnMeta("label", "Label", "Short candidate label.", CANDIDATE, sticky=True),
    ColumnMeta("calibration", "Calibration", "Win-probability calibration method.", CANDIDATE),
    ColumnMeta(
        "market_prob_weight",
        "Mkt blend",
        "Weight of the market probability in the blend.",
        CANDIDATE,
        "float",
        decimals=2,
    ),
    ColumnMeta(
        "market_prob_clamp",
        "Mkt clamp",
        "Maximum distance allowed from the market probability.",
        CANDIDATE,
        "float",
        decimals=2,
    ),
    ColumnMeta(
        "market_prob_source", "Mkt source", "Raw or no-vig market probabilities.", CANDIDATE
    ),
    ColumnMeta(
        "market_prob_blend_method",
        "Blend method",
        "Blend in probability or logit space.",
        CANDIDATE,
    ),
    ColumnMeta(
        "win_prob_use_uncertainty",
        "Uses σ",
        "Whether the quantile spread widens the win probability.",
        CANDIDATE,
        "bool",
    ),
    ColumnMeta("market_mode", "Market mode", "How market features enter the model.", CANDIDATE),
    ColumnMeta(
        "duration_seconds",
        "Duration (s)",
        "Walk-forward wall time.",
        CANDIDATE,
        "float",
        "lower",
        decimals=0,
    ),
    ColumnMeta(
        "wf_rank",
        "WF rank",
        "Rank among candidates by Brier then log loss.",
        CANDIDATE,
        "int",
        "lower",
    ),
)

WF_COMPARE_COLUMNS: list[str] = [
    "wf_rank", "label", "calibration", "market_prob_weight", "market_prob_clamp", "market_prob_source",
    "market_prob_blend_method", "win_prob_use_uncertainty", "market_mode",
    "brier", "log_loss", "reliability_ece", "pick_accuracy", "margin_mae", "total_mae",
    "expected_points_avg", "actual_points_avg", "games", "weeks", "duration_seconds",
]  # fmt: skip
