"""Measure how much of ``scripts/`` the current test suite already covers.

Run from the repository root:

    .venv/bin/python .agents/m60/scripts_coverage.py

It runs the whole pytest suite with coverage over ``scripts`` as well as the package and writes
a per-file table to ``SCRIPTS_COVERAGE.md``, with a projection of package statement coverage if
the files ``annotations.yaml`` proposes to move came into the package with today's tests. The
package coverage floor is not enforced here; the gate does that.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
TABLE = HERE / "SCRIPTS_COVERAGE.md"


def main() -> int:
    """Run the suite with coverage over scripts and write the per-file table."""
    with tempfile.TemporaryDirectory(prefix="scripts_coverage_") as tmp:
        return _measure(Path(tmp) / "coverage.json")


def _measure(raw: Path) -> int:
    """Run pytest writing the JSON report to ``raw`` and render the table."""
    result = subprocess.run(  # noqa: S603 - fixed argv built from this file
        [
            sys.executable,
            "-m",
            "pytest",
            "-q",
            "-p",
            "no:cacheprovider",
            "--cov=scripts",
            "--cov-fail-under=0",
            f"--cov-report=json:{raw}",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    tail = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""
    if not raw.exists():
        sys.stderr.write(f"pytest wrote no coverage report (exit {result.returncode})\n")
        return 1
    report = json.loads(raw.read_text(encoding="utf-8"))
    rows = []
    for name, data in sorted(report["files"].items()):
        if not name.startswith("scripts/"):
            continue
        summary = data["summary"]
        rows.append(
            (
                name,
                summary["num_statements"],
                summary["missing_lines"],
                summary["percent_covered"],
            )
        )
    lines = [
        "# Current test coverage of scripts/ (generated)",
        "",
        "Generated by `.venv/bin/python .agents/m60/scripts_coverage.py`; do not edit by hand.",
        f"pytest summary: `{tail}` (exit {result.returncode}).",
        "",
        "| file | statements | missing | covered % (branches included) |",
        "| --- | --- | --- | --- |",
    ]
    lines += [f"| `{n}` | {s} | {m} | {p:.1f} |" for n, s, m, p in rows]
    statements = sum(r[1] for r in rows)
    missing = sum(r[2] for r in rows)
    lines += [
        "",
        f"Total: {statements} statements, {missing} missing "
        f"({100 * (statements - missing) / max(statements, 1):.1f}% of statements covered).",
        "",
    ]
    annotations = yaml.safe_load((HERE / "annotations.yaml").read_text(encoding="utf-8"))
    moving = {
        name
        for name, disp in annotations.get("scripts", {}).items()
        if str(disp.get("disposition", "")).startswith("move")
    }
    pkg = [d["summary"] for n, d in report["files"].items() if n.startswith("nfl_predictor/")]
    pkg_statements = sum(x["num_statements"] for x in pkg)
    pkg_missing = sum(x["missing_lines"] for x in pkg)
    moved = [r for r in rows if r[0] in moving]
    moved_statements = sum(r[1] for r in moved)
    moved_missing = sum(r[2] for r in moved)
    now = 100 * (pkg_statements - pkg_missing) / max(pkg_statements, 1)
    projected = (
        100
        * (pkg_statements - pkg_missing + moved_statements - moved_missing)
        / max(pkg_statements + moved_statements, 1)
    )
    lines += [
        "Projection (statements only; the gate's 90% floor also counts branches, so it reads",
        "a little differently):",
        "",
        f"- Package today: {pkg_statements} statements, {pkg_missing} missing ({now:.1f}%).",
        f"- Files proposed to move ({len(moved)}): {moved_statements} statements, "
        f"{moved_missing} missing.",
        f"- Package after moving them with today's tests: {projected:.1f}%.",
        "",
        "Excluded from the projection: the `build_betting_report` part of `betting_pipeline.py`",
        "(proposed to move while the rest retires) and any code removed with the retirements.",
        "",
    ]
    TABLE.write_text("\n".join(lines), encoding="utf-8")
    sys.stdout.write("\n".join(lines))
    return 0 if result.returncode == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
